= Asciidoctor Docker Container
:sectnums:
:toc:
:source-highlighter: rouge

== The environment

This Docker container provides:

* Asciidoctor 2.0.0
* Asciidoctor.js
* Aciidoctor Diagram with Graphviz, Vega, Seqdiag, NetworkDiag, Blockdiag integration so you can use a wide range of diagrams
* Asciidoctor PDF (alpha)
* Asciidoctor EPUB3 (alpha)
* Source highlighting using Rouge, CodeRay or Pygments
* Asciidoctor backends
* Asciidoctor-confluence
* Lazybones (for Asciidoctor-revealjs)
* Inkscape
* Node 10.x and npm and yard

== How to use it

Just run:

[source,bash]
----
docker run -it -v <your directory>:/documents/ danyill/docker-asciidoctor
----

It will be directly mapped with [path]_/documents_ of the container.

Once started, you just have to create AsciiDoc files (in the directory mentioned above) and run Asciidoctor commands like:

* To run Asciidoctor on a basic AsciiDoc file:
+
[source,bash]
----
asciidoctor sample.adoc
asciidoctor-pdf sample.adoc
asciidoctor-epub3 sample.adoc
----

* To run AsciiDoc on an AsciiDoc file that contains diagrams:
+
[source,bash]
----
asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-pdf -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-epub3 -r asciidoctor-diagram sample-with-diagram.adoc
----

* To use Asciidoctor-backends use +-T+ with either `/asciidoctor-backends` or `$BACKENDS` followed by the backend you want to use. For example:
[source,bash]
----
asciidoctor -T /asciidoctor-backends/slim/dzslides myFile.adoc
#or
asciidoctor -T $BACKENDS/slim/dzslides myFile.adoc
----

* To use asciidoctor-confluence
+
[source, bash]
----
asciidoctor-confluence --host HOSTNAME --spaceKey SPACEKEY --title TITLE --username USER --password PASSWORD sample.adoc
----

* Batch mode. You can use it in a "batch" mode
+
[source, bash]
----
docker run --rm -v $(pwd):/documents/ danyill/docker-asciidoctor asciidoctor-pdf index.adoc
----

== How to update this container

Make changes:

. In the working path: 
+
[source,bash]
----
docker build --tag danyill/docker-asciidoctor:latest .
----

. We can build directly from the github repo with 
+
[source,bash]
----
docker build -t danyill/docker-asciidoctor:latest git@github.com:danyill/docker-asciidoctor.git
----

. Login to docker with `docker login`

. Push the new image with
+
[source,bash]
----
docker push danyill/docker-asciidoctor:latest
----

. Releasing a version
+
[source,bash]
----
docker build --tag danyill/docker-asciidoctor:1.0.0 --tag danyill/asciidoctor:latest .
docker push danyill/docker-asciidoctor:latest danyill/docker-asciidoctor:1.0.0
----

== Checking Errors

Run bash inside the container:

[source,bash]
----
docker run -i -t  danyill/docker-asciidoctor bash
----

If we have a failed build, take the preceding build's hash and enter it:

[source,bash]
----
docker run --rm -it <id_last_working_layer> bash -il
----

then run the previous command from the Dockerfile and then examine the logs.

